[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32G431KBTx"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "debug"

[profile.dev]
opt-level = 3
