[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF82840_xxAA with your chip as listed in `probe-rs-cli chip list`
#runner = "probe-rs-cli run --chip nRF52840_xxAA --probe 0483:3748:16004A002933353739303541"
runner = "probe-run --chip nRF52840_xxAA"

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
